<a href="https://colab.research.google.com/github/alen88925/py-test/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Start Numpy



##安裝Numpy


在終端機輸入指令
pip install numpy

##載入Numpy套件


In [3]:
import numpy as np

##建立ndarray物件

In [32]:
result=np.array([3,4,-5])
print(result)
print(result.size) #數量

[ 3  4 -5]
3


In [29]:
result=np.arange(20).reshape(4,5)
result1=np.vsplit(result,2)
print(result1)

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]


# 多維陣列(ndarray) 基礎運算

In [33]:
data1=np.array([3,-4,5])  #1x3
data2=np.array([2,-1,4])  #1x3
data3=np.array([[2,4,5,3],[8,3,-1,3],[5,2,6,-1]]) #3x4

##逐元運算(elementwise)

針對陣列每個資料，逐一進行基本運算。


In [ ]:
a1=data1+data2
a2=data1-data2
a3=data1*data2
a4=data1/data2
a5=data1>data2
a6=data1==data2
a7=data1<=data2
print(a7)

##矩陣運算(matrix)

針對兩個多維陣列，進行矩陣運算。


In [36]:
b1=data1.dot(data3)     #內積 1x4
b2=data1@data3       #內積 1x4
b3=np.outer(data1,data3)  #外積 3x12
print(b3)

[[  6  12  15   9  24   9  -3   9  15   6  18  -3]
 [ -8 -16 -20 -12 -32 -12   4 -12 -20  -8 -24   4]
 [ 10  20  25  15  40  15  -5  15  25  10  30  -5]]


##統計運算(statistics)


針對單一陣列，進行統計運算。


In [45]:
#統計運算的函式中，都可以加入axis來進行不同維度的運算。
c1=data3.sum()
c2=data3.sum(axis=0)  #Column 第一維度
c3=data3.sum(axis=1)  #Row 第二維度
c4=data3.min()
c5=data3.max()
c6=data3.cumsum()
c7=data3.mean()
c8=data3.std(axis=0)
print(c8)

[2.44948974 0.81649658 3.09120617 1.88561808]


# 多維陣列的索引(Index) & 切片(Slicing)

In [51]:
data4=np.array([
  [
   [2,4,3],[3,-1,1]
  ],
  [
   [8,3,2],[-1,3,-4]
  ],
  [
   [5,2,-2],[6,-1,-6]
  ]
]) #3x2x3

##索引(Index)

每個資料都有一個索引(編號)，從0開始遞增。

In [56]:
i1=data4[0,0,1]
print(i1)

4


##切片(Slicing)

以下語法取得特定陣列資料: 多維陣列**[開始索引 ：結束索引-1]**

In [59]:
#(...)&(:) 代表全都要
s1=data4[1:,...,:2]
s2=data4[1:,:,:2]
print(s1)
print(s2)

[[[ 8  3]
  [-1  3]]

 [[ 5  2]
  [ 6 -1]]]
[[[ 8  3]
  [-1  3]]

 [[ 5  2]
  [ 6 -1]]]


# 多維陣列的合併(Stacking) & 切割(Splitting)

In [61]:
data5=np.array([
  [2,4,5,3],
  [8,3,-1,3],
  [5,2,6,-1]
]) #3x4
data6=np.array([
  [8,3,-1,-3],
  [7,2,-5,3],
  [3,1,6,1]
]) #3x4

## 合併(Stacking)

將數個多維陣列，合併成一個。

In [64]:
s1=np.vstack((data5,data6)) #第一維度
s2=np.hstack((data5,data6)) #第二維度
print(s1)
print(s2)

[[ 2  4  5  3]
 [ 8  3 -1  3]
 [ 5  2  6 -1]
 [ 8  3 -1 -3]
 [ 7  2 -5  3]
 [ 3  1  6  1]]
[[ 2  4  5  3  8  3 -1 -3]
 [ 8  3 -1  3  7  2 -5  3]
 [ 5  2  6 -1  3  1  6  1]]


## 切割(Splitting)

將一個多維陣列，分割成數個。

In [67]:
s3=np.vsplit(data5,3) #第一維度
s4=np.hsplit(data5,2) #第二維度
print(s3)
print(s4)

[array([[2, 4, 5, 3]]), array([[ 8,  3, -1,  3]]), array([[ 5,  2,  6, -1]])]
[array([[2, 4],
       [8, 3],
       [5, 2]]), array([[ 5,  3],
       [-1,  3],
       [ 6, -1]])]
